version: "3.1"
services:
  db:
    image: postgres:11.7
    volumes:
      - ./docker/tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
